name: Deploy

on:
  push:
    tags:
      - 'release-v*'
      - 'dev-v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server via SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              cd /home/ubuntu/test
              git fetch --all
              git checkout ${{ github.ref_name }}
              git pull origin ${{ github.ref_name }}
              # pnpm install --frozen-lockfile
              # pnpm build
              # pm2 reload ien-backend || pm2 start dist/main.js --name ien-backend
